import { LogLevel, LoggerOptions } from '@diia-inhouse/types'

export const defaultOptions = {
    logLevel: LogLevel.INFO,
    maxArrayLength: 100,
    maxStringLength: 255,
    endLengthToLog: 10,
    maxObjectDepth: 8,
    maxObjectBreadth: 50,
    redact: {
        fields: [
            'inn',
            'itn',
            'client',
            'firstName',
            'lastName',
            'middleName',
            'firstname',
            'lastname',
            'middlename',
            'first_name',
            'last_name',
            'middle_name',
            'given_name',
            'family_name',
            'patronymic_name',
            'passportSeries',
            'passportNumber',
            'email',
            'addressOfRegistration',
            'addressOfBirth',
            'birthDay',
            'birthday',
            'date_birth',
            'fio',
            'passport',
            'phone',
            'address',
            'birthplace',
            'fullName',
            'full_name',
            'phoneNumber',
            'extraPhoneNumber',
            'refreshToken',
            'token',
            'fName',
            'lName',
            'mName',
            'DocNumberDRFO',
            'GivenName',
            'PatronymicName',
            'FamilyName',
            'surname',
            'patronymic',
            'rnokpp',
            'document',
            'firstNameUA',
            'lastNameUA',
            'middleNameUA',
            'serialNumber',
            'department',
            'departmentUA',
            'departmentEN',
            'birthPlaceUA',
            'birthPlaceEN',
            'recordNumber',
            'firstNameEN',
            'lastNameEN',
            'docNumber',
            'documentRegistrationPlaceUA',
            'currentRegistrationPlaceUA',
            'registrationPlace',
            'birthDate',
            'categories',
            'photo',
            'sign',
            'docIdentity',
            'collegeName',
            'facultyName',
            'educationType',
            'vehicleLicenseId',
            'website',
            'vin',
            'licensePlate',
            'dateReg',
            'dateFirstReg',
            'number',
            'residenceRegistrationPlace',
            'documentNumber',
            'password',
            'vault',
            'appPartnerId',
            'partnerToken',
            'partnerFullName',
            'residenceAddress',
            'displayName',
            'personalPhone',
            'content',
            'subjAddress',
            'subjPhone',
            'subjEmail',
            'subjDrfoCode',
            'oldLastName',
            'oldFirstName',
            'oldMiddleName',
        ],
        paths: [],
        fieldsToRedactFullname: [
            'value',
            'name',
            'title',
            'creditors',
            'pay_text',
            'order_description',
            'owner',
            'label',
            'shortText',
            'listName',
            'text',
            'textItems',
            'subject',
            'subjCn',
            'subjFullName',
            'accessibilityDescription',
            'documents',
        ],
        fieldsToRedactItn: ['label', 'paymentPurpose', 'subject', 'value'],
    },
} satisfies LoggerOptions
